---
title: "SDM Project"
author: "| Sai Prathyusha Pamulapati \n| UB PERSON ID: 50441868\n"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(42) # seed for any random generation
```



```{r}
#install.packages('tidyverse')
library(tidyverse) 
library(here)
library(corrplot)
```

```{r}
df <-  readr::read_csv(here("sales.csv"))

```

## no null values
```{r}
summary(is.na(df))
```

```{r}
library(ggplot2)
# Build the classification graph
ggplot(data = df, aes(x = Branch)) +
  geom_bar(aes(fill = Branch)) + 
  labs(title = "Branch Analysis",
       subtitle = "Which branch is the busiest?.",
       x = "Branches",y="Count")
```
```{r}
ggplot(df, aes(y=`Product line`)) + 
geom_bar(aes(fill = Gender)) + 
  labs(title = "Gender Analysis per Product Type",
       x = "Count",
       y = "Product Type")
```
```{r}
#ggplot(df, aes(y='Product line')) + 
#geom_bar(aes(fill = Branch)) + 
#  labs(title = "Braches having better sales for Product Type",
#      x = "Count",
#      y = "Product Type")

x <-  df$`Tax 5%`
y <- df$`gross income`
plot(x, y, col = "purple", main="Tax 5% as a function of the Gross Income",
  xlab="Tax 5%", ylab="Gross Income")

```
```{r}
x <-  df$`Unit price`
y <- df$`gross income`
plot(x, y, col = "violet", main="Unit Price Vs Gross Income",
  xlab="Unit Price", ylab="Gross Income")
```
